### ISSUE TITLE
Figure out how to solve dependency problems between services

### ISSUE THREAD

**Issue by kfichter** [plasma-group/plasma-core#48]
Several services are dependent on other services. For example, `MockWalletProvider` is dependent on `ChainService` to initialize the balances for some dummy accounts:

```
...

this.addresses.forEach((address, i) => {
  this.app.services.chain.addTransaction({
    from: address,
    to: address,
    range: {
      token: 'ETH',
      start: i * 1000000,
      end: (i + 1) * 1000000
    }
  })
})

...
```

However, this means that the whole thing breaks if `ChainService` doesn't exist at the time that `MockWalletProvider` needs it.

Currently, we're handling this problem by starting services in a particular order:

```
...

const services = [
  { type: this.options.dbProvider || DefaultDBProvider },
  { type: ChainService },
  { type: JSONRPCService },
  { type: this.options.operatorProvider || DefaultOperatorProvider },
  { type: this.options.walletProvider || DefaultWalletProvider }
]

...
```

I'm not sure if this is the best way to handle this problem. It seems like there should be a more robust way to start services such that services wait for their dependencies to exist.

**Comment by tarrencev** [comment]
A simple way to avoid this could be to inject `app` during the `start()` lifecycle method (rather than during construction) and moving cross service dependency logic, like `_initAccounts`, there too. Then we can be sure all services are instantiated before being called.

**Comment by kfichter** [comment]
Closing. From now on, services may only access other services after their start() calls.

**Comment by kfichter** [comment]
Aaaand now this is codified - all services will throw an error when trying to access any services that have not yet been started.
