### ISSUE TITLE
Figure out the average amount of gas used by `listToken`

### ISSUE THREAD

**Issue by kfichter** [plasma-group/plasma-core#70]
Tokens must be **listed** in the plasma chain contract before they can be deposited. We provide a wrapper to the `listToken` method in [ContractProvider](https://github.com/plasma-group/plasma-core/blob/master/src/services/contract/contract-provider.js):

https://github.com/plasma-group/plasma-core/blob/8a04fc8d85fd3200dcf975bd8c25149f5c6c0d1b/src/services/contract/contract-provider.js#L126-L142

We're currently using a high gas limit for this transaction (6,000,000) that isn't necessary. We need to run `listToken` several times to figure out the average gas used for this method.

**Comment by gakonst** [comment]
You can do `let gasValue = await this.contract.methods.listToken(tokenAddress, 0).estimateGas()` and use that instead of the hardcoded amount

**Comment by kfichter** [comment]
Good point. Sometimes that returns infinity but will check.

**Comment by nourharidy** [comment]
It only returns infinity only in 1 of these cases:
(A) estimatedGas transaction results in an invalid EVM state (e.g. reverts).
(B) transaction includes an actual infinite for loop
(C) arguments that are dependent upon for gas estimation are missing (e.g. address of an external contract that is called by the tx recipient contract)

Juts to be safe, you could depend on estimateGas and fallback to the hardcoded 6,000,000 gas if it returns infinity.
